export let productos = [
  {
    id: 1,
    titulo: "Airpods Apple",
    precio: 209.99,
    stock: 25,
    descripcion: "Los AirPods te brindan una experiencia inalámbrica increíble, pues ahora te ofrecen muchas horas de audio y conversación y la posibilidad de usarlos con un estuche de carga inalámbrica. Sácalos del estuche y estarán listos para funcionar con todos tus dispositivos. Póntelos y se conectarán al instante, como por arte de magia, para brindarte un sonido rico en matices y de alta calidad.",
    summaryDescripcion: "Auriculares Bluetooth Airpods Apple",
    categoria: "Telefonia-Accesorios",
    review:39,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429875/appleairpods_tl7hqc.jpg",
  },
  {
    id: 2,
    titulo: "Nintendo Switch Oled",
    precio: 580,
    stock: 10,
    descripcion: "Te presentamos la última consola que se une a la familia Nintendo Switch.La nueva consola cuenta con una vibrante pantalla OLED de 7 pulgadas (17.78 cm), un soporte ajustable y amplio, una base con puerto LAN para conexión por cable, almacenamiento interno de 64 GB y audio mejorado.",
    summaryDescripcion: "La nueva consola cuenta con una vibrante pantalla OLED de 7 pulgadas (17.78 cm), un soporte ajustable y amplio, una base con puerto LAN para conexión por cable, almacenamiento interno de 64 GB y audio mejorado.",
    categoria: "Gaming-Consolas",
    review:23,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429875/nintendoswoled_svr7nm.jpg",
  },
  {
    id: 3,
    titulo: "Mouse Gamer SteelSeries",
    precio: 89,
    stock: 11,
    descripcion: "El primer ratón inalámbrico de verdadero rendimiento .El exclusivo Quantum Wireless TM ofrece juegos de 1000Hz (1ms) sin retrasos . 15-minutos de carga rápida ofrece 10+ horas de juego .Sensor de profundidad secundario dedicado para detección instantánea de levantamiento.256 Configuraciones de ajuste de peso decentro de gravedad",
    summaryDescripcion: "Raton inalambrico SteelSeries 16.000DPI,RGB",
    categoria: "Perifericos",
    review:15,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429874/mousegamersteelseries_wnkwqz.jpg",
  },
  {
    id: 4,
    titulo: "Roku Streaming Device",
    precio: 49,
    stock: 20,
    descripcion: "Roku® Streaming Stick® 4K es más rápido y potente que nunca. El receptor de wifi® de largo alcance rediseñado está supercargado con hasta el doble de velocidad; exactamente lo que necesitas para reproducir por streaming sin interrupciones en una increíble calidad de imagen 4K, Dolby Vision® y HDR10+.",
    summaryDescripcion:"Roku® Streaming Stick® 4K es más rápido y potente que nunca.",
    categoria: "Perifericos",
    review:28,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429874/rokustreamingdevice_hfrljw.jpg",
  },
  {
    id: 5,
    titulo: "Notebook HP ENVY 13/Core™ i7",
    precio: 1345,
    stock: 8,
    descripcion: " Notebook HP ENVY 13-ba1124la / Core™ i7, 8 Gb Ram, Disco Sólido 512 Gb, Intel® Optane™ de 32 GB, Full HD IPS, Bang & Olufsen, Bluetooth® Windows 10 (2K6V7LA) . Crea en cualquier momento y en cualquier lugar, con la nueva HP ENVY Laptop 13 con batería para todo el día. Mantén tus contenidos y creaciones de forma segura con su avanzada tecnología de seguridad tan fácil como presionar un botón. ",
    summaryDescripcion: "Core™ i7, 8 Gb Ram, Disco Sólido 512 Gb, Intel® Optane™ de 32 GB, Full HD IPS",
    categoria: "Notebook",
    review:12,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429874/notebookhp_igakye.jpg",
  },
  {
    id: 6,
    titulo: "Teclado Razer v10",
    precio: 99,
    stock: 12,
    descripcion: "El que fuera pionero vuelve para reafirmar su dominio. Siente la diferencia con el Razer BlackWidow V10: respaldado por su legado como primer y más icónico teclado mecánico para juegos y equipado con funciones nuevas y mejoradas, incluidos nuestros switches mundialmente reconocidos.",
    summaryDescripcion: "Teclado gamer Razer v10",
    categoria: "Perifericos",
    review:8,
    img: "https://res.cloudinary.com/dszdytbbc/image/upload/v1681429874/tecladogamerrazer_exvyv7.jpg",
  },
];
